"""Checks for the upload pack.

The pack is generated by an LLM, so the field shapes vary run to run — the
normalisation is what stops a chatty response from putting a character per
hashtag or a scene index off the end of the image list.
"""

import pytest
from PIL import ImageFont

from pipeline import script
from pipeline.assemble import _FONT, _wrap


def _pack(monkeypatch, payload, n_scenes=10):
    monkeypatch.setattr(script, "_kenari_script", lambda prompt, model: payload)
    return script.generate_post_pack("narration", "source", n_scenes,
                                     provider="kenari", model="m")


class TestGeneratePostPack:
    def test_hashtags_as_a_string(self, monkeypatch):
        pack = _pack(monkeypatch, {"title": "T", "hashtags": "#shorts #storytime"})
        assert pack["hashtags"] == ["#shorts", "#storytime"]

    def test_hashtags_as_a_list_without_hashes(self, monkeypatch):
        pack = _pack(monkeypatch, {"title": "T", "hashtags": ["shorts", "storytime"]})
        assert pack["hashtags"] == ["#shorts", "#storytime"]

    def test_scene_index_is_clamped_into_the_image_list(self, monkeypatch):
        pack = _pack(monkeypatch, {"title": "T", "thumbnail_scene": 99}, n_scenes=10)
        assert pack["thumbnail_scene"] == 10

    def test_scene_index_of_zero_becomes_the_first_scene(self, monkeypatch):
        pack = _pack(monkeypatch, {"title": "T", "thumbnail_scene": 0})
        assert pack["thumbnail_scene"] == 1

    def test_a_non_numeric_scene_falls_back_to_the_first(self, monkeypatch):
        pack = _pack(monkeypatch, {"title": "T", "thumbnail_scene": "the dramatic one"})
        assert pack["thumbnail_scene"] == 1

    def test_title_is_required(self, monkeypatch):
        with pytest.raises(RuntimeError, match="no title"):
            _pack(monkeypatch, {"description": "d"})

    def test_thumbnail_text_is_uppercased(self, monkeypatch):
        pack = _pack(monkeypatch, {"title": "T", "thumbnail_text": "she knew"})
        assert pack["thumbnail_text"] == "SHE KNEW"


class TestWrap:
    def test_never_exceeds_the_pixel_width(self):
        font = ImageFont.truetype(_FONT, 150)
        lines = _wrap("EVERYONE WAS WRONG ABOUT HER AND NOBODY SAID A WORD", font, 900)
        assert len(lines) > 1
        for line in lines:
            assert font.getbbox(line)[2] - font.getbbox(line)[0] <= 900

    def test_a_word_wider_than_the_limit_still_produces_a_line(self):
        """Otherwise the loop emits nothing and the headline silently vanishes."""
        font = ImageFont.truetype(_FONT, 150)
        assert _wrap("UNBREAKABLE", font, 10) == ["UNBREAKABLE"]

    def test_short_text_stays_on_one_line(self):
        font = ImageFont.truetype(_FONT, 150)
        assert _wrap("MOTHER", font, 900) == ["MOTHER"]
